# Generated by Django 5.1.4 on 2025-02-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saint', '0003_filling_flour_sauce_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flour', models.CharField(blank=True, max_length=255)),
                ('filling', models.CharField(blank=True, max_length=255)),
                ('topping', models.CharField(blank=True, max_length=255)),
                ('sauce', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
