# Generated by Django 5.1.4 on 2025-02-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saint', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='queue_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('confirmed', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น')], default='pending', max_length=20),
        ),
    ]
