# Generated by Django 5.1.4 on 2025-02-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saint', '0006_ordergroup_remove_order_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergroup',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='ordergroup',
            name='total_quantity',
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='queue_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
