# Generated by Django 5.1.4 on 2025-02-27 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saint', '0008_order_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('confirmed', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น รอชำระเงิน'), ('paid', 'ชำระเงินเสร็จสิ้น')], default='pending', max_length=20),
        ),
    ]
