# Generated by Django 5.1.6 on 2025-02-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saint", "0010_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอดำเนินการ"),
                    ("Order received", "รับออเดอร์แล้ว"),
                    ("confirmed", "กำลังดำเนินการ"),
                    ("completed", "เสร็จสิ้น รอชำระเงิน"),
                    ("paid", "ชำระเงินเสร็จสิ้น"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
